version: '3.8'

networks:
    symfony:
        driver: bridge

services:
    # nginx
    nginx:
        build:
            context: ./docker-files/nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
            - "80:80"
        networks:
            - symfony
        volumes:
            - ./app:${APP_DIR_IN_CONTAINER:-/app}
            - ./docker-files/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
    # php
    php:
        build:
            context: ./docker-files/php
            args:
                app_dir: ${APP_DIR_IN_CONTAINER:-/app}
            dockerfile: Dockerfile
        container_name: php
        user: 1000:1000
        ports:
            - "9000:9000"
        networks:
            - symfony
        volumes:
            - ./app:${APP_DIR_IN_CONTAINER:-/app}
        depends_on:
            -   mysql
    # mysql
    mysql:
        image: mysql:8
        container_name: mysql
        ports:
            - "4306:3306"
        networks:
            - symfony
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret321}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret123}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony-real}
    # node
    front:
        container_name: front
        build:
            context: ./docker-files/node
            args:
                app_dir: ${APP_DIR_IN_CONTAINER:-/app}
            dockerfile: Dockerfile
        volumes:
            - ./app:${APP_DIR_IN_CONTAINER:-/app}
