<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20221021063241 extends AbstractMigration
{
    private $user_uuid;

    public function getDescription(): string
    {
        return '';
    }

    public function preUp(Schema $schema): void
    {
        parent::preUp($schema); // TODO: Change the autogenerated stub
        $this->user_uuid = $this->connection->executeQuery('SELECT uuid FROM public."user"')->fetchOne();
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        if ($this->user_uuid) {
            $this->addSql('UPDATE micro_post set user_uuid = :user_uuid WHERE user_uuid IS NULL', ['user_uuid' => $this->user_uuid]);
        }

        $this->addSql('ALTER TABLE micro_post ALTER user_uuid SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE micro_post ALTER user_uuid DROP NOT NULL');
    }
}
